name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: latest

    - name: Install dependencies
      run: |
        uv pip install -e ".[dev]" --system

    - name: Verify dataset checksums
      env:
        BICAM_SECRET_KEY: ${{ secrets.BICAM_SECRET_KEY }}
        BICAM_CREDENTIAL_ENDPOINT: ${{ secrets.BICAM_CREDENTIAL_ENDPOINT }}
      run: |
        python scripts/verify_checksums.py
      continue-on-error: true

    - name: Build and publish
      env:
        BICAM_SECRET_KEY: ${{ secrets.BICAM_SECRET_KEY }}
        BICAM_CREDENTIAL_ENDPOINT: ${{ secrets.BICAM_CREDENTIAL_ENDPOINT }}
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        # Create required .env files for build script
        mkdir -p scripts/credentials
        echo "BICAM_SECRET_KEY=${{ secrets.BICAM_SECRET_KEY }}" > scripts/credentials/.env
        echo "BICAM_CREDENTIAL_ENDPOINT=${{ secrets.BICAM_CREDENTIAL_ENDPOINT }}" >> scripts/credentials/.env

        # Create root .env file for PyPI token
        echo "PYPI_API_TOKEN=${{ secrets.PYPI_API_TOKEN }}" > .env

        # Build and publish
        ./scripts/build_and_publish.sh --publish

        # Clean up
        rm -f .env
        rm -f scripts/credentials/.env
